### PR TITLE
added extern "C" to headers

### PR DESCRIPTION
**Pull request by GravisZro**
this fixes linker issues for c++ code that uses e-lib.
see https://parallella.org/forums/viewtopic.php?f=13&t=2310 for details.

### CODE REVIEW

**Comment by olajep** [comment]
I think it would be much cleaner to put the extern "C" directive in e_lib.h instead of every header file. That way the patch goes down from 65 lines to 6.

Thanks,
Ola

**Comment by GravisZro** [comment]
if you only put it in e_lib.h, including other headers will result in breaking too.  so if you just wanted to include e_regs.h, it would end up breaking.

**Comment by olajep** [comment]
So I like the idea but I really think you're over-complicating it.

You cannot break something that is already "broken". I.e.,  we know that there is no code out there that depends on extern "C" in every elib header file.

The library is really tiny so there is no reason to include anything but e-lib.h. You will save what, a millisecond in compilation time? And in the API reference e-lib.h is the only header file that is ever mentioned for eLib. So including another header file that happens to be in the library is already in the gray area.

Just put the extern "C" guard in e_lib.h, that'll work for everyone and you'll be sure that the entire library will be covered automagically even if more files are added.

Thanks,
Ola

**Comment by GravisZro** [comment]
if you dont add the extern "C" to each header then at least add code so that will prevent people from including the other headers directly.

**Comment by jeremybennett** [comment]
Ola, GravisZro,

A general C/C++ programming principle is that headers should include anything they depend on, and it should not matter if you include them more than once.  So either you need to put extern "C" in each header, or each header needs to include e_lib.h.  Guards solve the problem of multiple inclusion.

For use with C++, you should also make sure the headers are namespace clean.

HTH,


Jeremy

**Comment by olajep** [comment]
> if you dont add the extern "C" to each header then at least add code so that will prevent people from including the other headers directly.

That might be a good idea. In a perfect world it should have been in there from the beginning. The problem now is it will break compilation of existing programs that include those headers. Error message can be made be pretty self explanatory though  "error: Don't include foo.h, use e-lib.h".

But then we need to add those checks to every file...

So ok you've convinced me :smiley:. Let's add the extern C clause to every header file then.

Please make the patch against the master branch. Put the extern "C" directly after the include guards. It seems to be missing in e-trace.h. And please remove things like these from the patch:
```diff
-#include "e_types.h"
+#include <e_types.h>
```

Otherwise if you're ok with it I can modify the patch and apply it myself.


Thanks,
Ola

**Comment by GravisZro** [comment]
ok, i've normalized the headers to use quotes instead of angle brackets as requested.

**Comment by olajep** [comment]
Sorry, I should have been more clear. What I meant was it doesn't belong in the patch at all.
I'll just fix it.

If I could just have your full name


You can set it with 
```
git config --global user.name "My Name"
```

Thanks,
Ola

**Comment by GravisZro** [comment]
*> What I meant was it doesn't belong in the patch at all.*
the headers should be consistent, regardless of which patch fixes them.

**Pull request closed without merging**
